
swagger : "2.0"
info: 
  title: "ELECITY-API"
  description: "this is the documentation for the ELECITY API"
  version: "1.0.0"
  contact:
    email: "thecandyman@gmx.fr"
  licence:
    name: "Apache 2.0"
    url : "http://apache.org"
  servers: 
    -url: "http://localhost:5000/"
    description: This is my local server


schemes: [http,https]
  
paths:
  /api/v1/users:
   get:
      summary: Retuns all users in array
      description: It returns all the users of the ELECITY API
      responses:
        200:
           description: Success Request
           schema:
             type: array
             items:
              type: object
              properties: 
                 _id:
                  type: "string"
                 first_name:
                  type: "string"
                 last_name:
                  type: string
                 birth_date:
                  type: string
                 phone:
                  type: string
                 mail: 
                  type: string
                 password:
                  type: string 
                 role:
                  type: string
                 createAt: 
                  type: string
                 updateAt: 
                  type: string
                 address: 
                  type: object
                  properties:
                    road:
                      type: string
                    zipcode:
                      type: number
                    city: 
                      type: string              
        400:
          description: User Error
          schema:
            type: string
            example: " User Error"
        
        500:
          description: Internal Server Error
          schema:
            type: string
            example: "Internal Server Error"

  /api/v1/users/{:id}:
   get:
     summary: Returns user with his ID
     description: It returns one user of the ELECITY API
     parameters: 
      - name: :id
        in: path
        required: true
        schema:
          type: integer
        responses:
        200:
          description: Success Request
          schema:
              type: object
              properties: 
                 _id:
                  type: object
                 first_name:
                  type: "string"
                 last_name:
                  type: string
                 birth_date:
                  type: string
                 phone:
                  type: string
                 mail: 
                  type: string
                 password:
                  type: string 
                 role:
                  type: string
                 createAt: 
                  type: string
                 updateAt: 
                  type: string
                 address: 
                  type: object
                  properties:
                    road:
                      type: string
                    zipcode:
                      type: number
                    city: 
                      type: string              
        400:
          description: User Error
          schema:
            type: string
            example: "User Error"
        500:
          description: Internal Server Error
          schema:
            type: string
            example: "Internal Server Error"








    
  


  



